# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Steve Swift Pty Ltd
email: steve@steveswift.com.au
description: >-
  Award-winning airworthiness consulting, training and expert witness services
baseurl: "/steveswift.com.au"
url: "https://walknuts.github.io"
permalink: pretty
future: true

linkedin_username: steve-swift-41ab5a42

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

exclude:
  - migration/

# frontmatter defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
